Added PublishEventWithMetadata
dapr/go-sdk pull request #173
Opened 2021-06-15 15:55 UTC by ItalyPaleAle

Fixes #164

2021-06-16 00:03 UTC, berndverst requested changes

2021-06-16 00:03 UTC, berndverst commented on client/pubsub_test.go
> +			"ttlInSeconds": "120",
Could you please change the metadata to something else so people don't get the idea they should set message expiration this way?

2021-06-16 00:19 UTC, berndverst commented
LGTM

If you are looking for other contributions related to this:
- Would be cool if we had an integration test that also sets up Kafka and then sets the TTL (which is what you implemented this feature for @ItalyPaleAle) using the GO SDK
- Update the Go SDK Readme to show an example that sets the TTL: https://github.com/dapr/go-sdk/#pubsub
- Update the docs at https://docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-message-ttl/ (this would need to go into the 1.3 branch)

2021-06-16 00:20 UTC, berndverst approved these changes

2021-06-16 00:21 UTC, berndverst commented
@yaron2 can you please review this PR also and merge if it looks good to you?

2021-06-16 16:35 UTC, tanvigour approved these changes
Looks good to me. Thanks @ItalyPaleAle !

2021-06-16 17:47 UTC, ItalyPaleAle commented
@yaron2 as I was talking to Bernd yesterday over Teams, while this PR does fix 164 perhaps there may be a better approach with what I proposed in 174. Can you take a look and let me know if I should scrap this PR? If you prefer the approach in 174, i should be able to make a new PR fairly quickly.

2021-06-18 22:17 UTC, yaron2 commented
> @yaron2 as I was talking to Bernd yesterday over Teams, while this PR does fix 164 perhaps there may be a better approach with what I proposed in 174. Can you take a look and let me know if I should scrap this PR? If you prefer the approach in 174, i should be able to make a new PR fairly quickly.

Thanks for taking a look at this, I agree that this can be done in a different way. Please see my comment here: https://github.com/dapr/go-sdk/issues/174#issuecomment-864299374.

I'm closing this PR for now, we can re-open if needed.

2021-06-18 22:17 UTC, closed without merging