Allow setting own gRPC server when calling `NewService`
dapr/go-sdk pull request #400
Opened 2023-05-19 13:07 UTC by pimmerks

We are building an application that exposes it's own gRPC service, it also needs to subscribe to the dapr pub/sub component.

Currently we are allowed to set the listener, but this is not enough, as we found that about half of the time, our own gRPC server responds, and the other half of the time the dapr service responds with an `unknown service xxx.xxx`.

If this is merged, the user is allowed to set their own grpcServer with the `NewServiceWithGrpcServer()` func.

In issue https://github.com/dapr/go-sdk/issues/237 the same problem has been found.

2023-05-19 15:57 UTC, JoshVanL requested changes
Thanks @pimmerks, this seems like a sensible extension to me :slightly_smiling_face:

2023-05-19 15:57 UTC, JoshVanL commented on service/grpc/service.go
> +	}
Prob don't really need a new variable here.

```suggestion
	if grpcServer == nil {
		grpcServer = grpc.NewServer(opts...)
	}
```

2023-05-19 15:57 UTC, JoshVanL commented on service/grpc/service.go
>  	s.grpcServer = gs
```suggestion

	pb.RegisterAppCallbackServer(grpcServer, s)
	pb.RegisterAppCallbackHealthCheckServer(grpcServer, s)
	s.grpcServer = grpcServer
```

2023-05-19 16:07 UTC, JoshVanL approved these changes

2023-05-20 15:01 UTC, yaron2 approved these changes

2023-05-20 15:01 UTC, merged