PR template added
dapr/go-sdk pull request #484
Opened 2023-12-14 19:08 UTC by sadath-12

Added pr template as suggested in #449

2023-12-18 07:38 UTC, daixiang0 approved these changes

2023-12-20 13:45 UTC, mikeee requested changes
I believe the descriptions or context should be in a comment so can be ignored on open rather than having to remove/delete the placeholder text.

2023-12-23 05:58 UTC, sadath-12 commented
> Me

> I believe the descriptions or context should be in a comment so can be ignored on open rather than having to remove/delete the placeholder text.

Just felt if we need to make sure the contributor must always provide information of what he did instead of making it optional . Please let me know if I am thinking it in right way

2023-12-27 06:10 UTC, daixiang0 commented on .github/pull_request_template.md
> +_Please explain the changes you've made_
Hide it.

2023-12-27 06:10 UTC, daixiang0 commented on .github/pull_request_template.md
> +We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.
Same as above.

2023-12-27 11:01 UTC, sadath-12 commented
thanks done @daixiang0

2023-12-27 17:05 UTC, mikeee commented
To clarify my opinion is that we should comment out the placeholder/descriptive text so that we provide an indication of what to include and does not include it.

2023-12-27 17:05 UTC, mikeee commented
To clarify - my opinion is that we should comment out the placeholder/descriptive text so that we provide an indication of what to include and does not include it.

2023-12-28 02:27 UTC, daixiang0 commented
> To clarify - my opinion is that we should comment out the placeholder/descriptive text so that we provide an indication of what to include and does not include it.

Agree, @sadath-12 please comment rather than delete.

2023-12-28 04:27 UTC, sadath-12 commented
yeah I get it now thanks @daixiang0  @mikeee

2023-12-28 04:51 UTC, daixiang0 approved these changes

2023-12-28 04:51 UTC, merged