tests: state_manger_test.go
dapr/go-sdk pull request #486
Opened 2023-12-16 07:01 UTC by sadath-12

Covers test cases for ```actor/state/state_manager.go```

2023-12-20 14:25 UTC, mikeee requested changes
Is this a WIP?

2023-12-23 12:49 UTC, sadath-12 commented
> Is this a WIP?

not currently . any 

> Is this a WIP?

Nope its done . Any further suggestions ?

2024-01-06 23:49 UTC, mikeee commented
> > Is this a WIP?
> 
> Nope its done . Any further suggestions ?

Apologies, I have a bad habit of reviewing when it's late - I'm not sure if I'm reading this correctly but this PR implements any testing as intended. You're essentially declaring a mock, telling it what to expect (and return) and then giving it what it expects. There is nothing being passed back to the test runtime either.

2024-01-06 23:51 UTC, mikeee commented
> > Is this a WIP?
> 
> Nope its done . Any further suggestions ?

Apologies, I have a bad habit of reviewing when it's late - I'm not sure if I'm reading this correctly but I don't think this PR implements any testing as intended. You're essentially declaring a mock, telling it what to expect (and return) and then giving it what it expects. There is nothing being passed back to the test runtime either.

2024-01-07 06:48 UTC, sadath-12 commented
Then I think we should either correct or implement the mock server properly then we can extend more tests as this pr was just meant to add some minimal tests if we see the issue description also other tests related to statemanager in this repo are not doing anything

2024-01-07 12:09 UTC, mikeee commented
I'm not sure what you mean, if I'm reading the contents of this PR correctly - no tests are added.

What other tests are you referring to?

2025-08-07 20:21 UTC, mikeee commented
Closing as this is stale, feel free to reopen if anything changes

2025-08-07 20:21 UTC, closed without merging