workflows support reuse id policy
dapr/go-sdk pull request #637
Opened 2024-10-11 11:39 UTC by famarting

# Description

Implements the missing bits to support workflows reuse id policy

## Issue reference

Please reference the issue this PR will close: #493

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2024-10-14 13:38 UTC, mikeee requested changes
I think surfacing this struct as an option is quite confusing in its current form, could the function possibly be refactored to not require another (internal) struct from `microsoft/durabletask-go` and/or document this before merge?

2024-10-15 07:36 UTC, famarting commented
> I think surfacing this struct as an option is quite confusing in its current form, could the function possibly be refactored to not require another (internal) struct from `microsoft/durabletask-go` and/or document this before merge?

done

2024-10-18 16:55 UTC, mikeee commented on workflow/client.go
> +	Action          api.CreateOrchestrationAction
Could these types be defined/wrapped as part of the go-sdk and parsed in the options function below?

2024-10-23 14:15 UTC, mikeee approved these changes

2024-10-23 15:20 UTC, famarting commented
merge please

2024-10-30 16:05 UTC, merged