worflows: activity retry policy
dapr/go-sdk pull request #644
Opened 2024-10-25 11:19 UTC by famarting

# Description

first part of https://github.com/dapr/go-sdk/issues/541

also updated one of the existing examples to show how activity retry policies can be used

## Issue reference

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2024-10-25 13:51 UTC, cicoyle approved these changes
lgtm

2024-10-25 16:41 UTC, mikeee reviewed
Looks like a solid implementation of retry policies for activities, just one potential signature refactor to accommodate the future addition of workflow retry policies. Also an ask - would it be possible to implement a simple activity that does continually fail - to test the retry logic?

2024-10-25 16:41 UTC, mikeee commented on workflow/activity_context.go
> +func RetryPolicy(policy ActivityRetryPolicy) callActivityOption {
Would this be better suited as `ActivityRetryPolicy`?

2024-10-25 16:41 UTC, mikeee commented on workflow/activity_context.go
> +func (opts *callActivityOptions) getRetryPolicy() *task.ActivityRetryPolicy {
As above

2024-10-31 10:52 UTC, famarting commented
good to go

2024-11-04 15:57 UTC, famarting commented
can we merge?

2024-11-04 16:10 UTC, mikeee commented
Can you please add a test for the activity to retry - I think it's crucial to validate this so we have some visibility if it breaks

2024-11-04 16:10 UTC, mikeee reviewed
Can you please add a test for the activity to retry - I think it's crucial to validate this so we have some visibility if it breaks

2024-11-08 15:17 UTC, mikeee requested changes
Thanks for adding tests, just need to register the new activity

2024-11-08 15:17 UTC, mikeee commented on examples/workflow/main.go
The new activity hasn't been registered and isn't being invoked

2024-11-08 15:30 UTC, famarting commented on examples/workflow/main.go
oops 😄

2024-11-08 16:16 UTC, mikeee approved these changes
lgtm

2024-11-14 05:02 UTC, merged